# Generated by Django 5.0.4 on 2024-04-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('mpaaRatingTypto', models.CharField(max_length=50)),
                ('mpaaRatingLabel', models.CharField(max_length=255)),
                ('userRating', models.IntegerField()),
                ('genre', models.ManyToManyField(to='movie.genres')),
            ],
        ),
    ]
